### PR TITLE
RLS v0.4.0

### PR DESCRIPTION
**Pull request by andrewseidl**

### CODE REVIEW

**Comment by andrewseidl** [comment]
@TomAugspurger Could you merge one last time? I've added myself as a recipe-maintainer, so should be able to do it myself in the future.

**Comment by TomAugspurger** [comment]
👍

Do you want to re-render the recipe with the latest conda-forge CI stuff? I think if you `@conda-forge-admin please rerender`, a bot will do the rerender and update the PR.

**Comment by TomAugspurger** [comment]
Oh, I guess the bot responds, even when in backticks :)

**Comment by TomAugspurger** [comment]
Hmm the failure on the linux worker seems to be a conda / conda-smithy issue.

> requests.exceptions.HTTPError: 502 Server Error: Bad Gateway for url: https://conda.anaconda.org/conda-forge/noarch/repodata.json

Seems to be hitting other repos: https://github.com/conda-forge/smesh-feedstock/pull/13

@jakirkham any guesses on what could be causing that?

**Comment by jakirkham** [comment]
Sounds like an Anaconda.org connectivity issue. Maybe you can file an issue with them internally? ;) Have seen a few of these intermittently today. Restarted the build for you. :)

**Comment by TomAugspurger** [comment]
Ah, thanks!

**Pull request merged**
