### PR TITLE
Make pyarrow >= 0.10

### PR DESCRIPTION
**Pull request by randyzwitch**
Checklist
* [x] Used a fork of the feedstock to propose changes
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/conda_smithy.html#how-to-re-render ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by randyzwitch** [comment]
@conda-forge-admin, please rerender

**Comment by randyzwitch** [comment]
@xhochy Since you work on Arrow...do I need to cap this at `<0.12`? Obviously pyarrow 0.12 isn't out, so I can't know that it's compatible, but I wouldn't expect there would be any incompatibility as we only use the most basic of Arrow functionality.

**Comment by xhochy** [comment]
@randyzwitch Looking at the `pymapd` sources: Is there still anything that needs to be compiled or it this a pure Python package? If so, this would make things a lot simpler.

**Comment by randyzwitch** [comment]
This should be a pure python package now, other than the dependencies that call out to C++

**Comment by xhochy** [comment]
@randyzwitch Cap it a `<0.12`, if it works with 0.12, we can just bump the version constraint.

**Comment by xhochy** [comment]
Also I made a PR to simplify the build matrix as we don't need to build for the different systems but can have a generic package.

**Comment by randyzwitch** [comment]
Great, thanks! So when your new PR passes, should I merge that first, then do the pyarrow cap?

**Comment by xhochy** [comment]
Feel free to continue here. My PR is currently failing :(

**Comment by randyzwitch** [comment]
@conda-forge-admin, please rerender

**Comment by randyzwitch** [comment]
I merged your PR @xhochy and capped this one at <0.12...do I need to bump the build number here before I merge it, since your PR is already build 1001?

**Pull request merged**
