### PR TITLE
Remove RBC pinning

### PR DESCRIPTION
**Pull request by xmnlab**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

This PR aims to remove RBC pinning

### CODE REVIEW

**Comment by xmnlab** [comment]
Probably we can remove RBC pinning here. @conda-forge/pymapd any feedback abou this? thanks!!

**Review by pearu — APPROVED** [review]
LGTM

**Comment by xmnlab** [comment]
@andrewseidl @jclay do you have any opinion about removing rbc pinning?

**Comment by jclay** [comment]
LGTM 👍

**Review by jclay — APPROVED** [review]

**Review by andrewseidl — APPROVED** [review]

**Pull request merged**
